# -*- coding: utf-8 -*-
"""
/***************************************************************************
 direccGeoRef
                                 A QGIS plugin
 georeferenciar domicilios mediante GeoRef
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-09
        copyright            : (C) 2025 by jlmw78
        email                : jlmw78@jlmw78.jlmw78
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load direccGeoRef class from file direccGeoRef.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .direcciones_2_GeoRef import direccGeoRef
    return direccGeoRef(iface)
